# Generated by Django 3.2 on 2021-04-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isbn',
            old_name='title',
            new_name='book_title',
        ),
        migrations.RenameField(
            model_name='isbn',
            old_name='book_isbn',
            new_name='isbn',
        ),
    ]
